#if !canImport(ObjectiveC)
  import XCTest

  extension SpeculidTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpeculidTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(SpeculidTests.__allTests__SpeculidTests)
    ]
  }
#endif
